# Write your MySQL query statement below
WITH FIRST_LOGIN AS(
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOG
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) 

select ROUND(
    COUNT(ACTIVITY.player_id) / COUNT(FIRST_LOGIN.PLAYER_ID) ,2
) as fraction
from FIRST_LOGIN left join ACTIVITY
on FIRST_LOGIN.PLAYER_ID= ACTIVITY.PLAYER_ID and event_date = Date_add(FIRST_LOG, INTERVAL 1 Day)

;